### ISSUE TITLE
TNT Not Falling Bug

### ISSUE THREAD

**Issue by Johnsonk79** [thebigsmileXD/TNTRun#1]
Hello! I have tried the first version but when you stand on edges, TNT does not fall, so I was wondering if the newest version have already fixed that bug?

**Comment by inxomnyaa** [comment]
No, that bug still exists. I can also not find a proper solution for it.. When i remove more blocks, players suddenly start falling for no reason (block under them disappears), when i change it to the blocks the AABB of the player collides with, the same also happens.. Imagine running and the block you are jumping to disappears..

**Comment by Johnsonk79** [comment]
So is there no way to fix this problem yet? If so that's just sad :(

**Comment by inxomnyaa** [comment]
It works alot better now, you can not stay in the same spot for some seconds and not on corners

**Comment by Johnsonk79** [comment]
thx!
