### ISSUE TITLE
VoidDeath

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/TNTRun#2]
Whenever someone falls in the void on my server in the chat it says "KimeraCraft" i removed it from happening but may you please fix it for other people who use the plugin

**Comment by inxomnyaa** [comment]
Can you please explain what exactly is happening and what you did to fix it

**Comment by ghost** [comment]
What is happening is that whenever someone dies the the void in blue the chat says "KimeraCraft" what i did to fix it was i went into the code and i simply chaged the message to someone like "vote for our serever" so it didnt say "kimeracraft"

**Comment by inxomnyaa** [comment]
This is not a bug. This is a cosmetic feature request. The message appears to inform players that that specific player lost.
